# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    identifier: Home
  - name: About
    url: '#about'
    weight: 11
    parent: Home
  - name: Terms & Conditions
    url: "terms"
    weight: 12
    parent: Home
  - name: News
    weight: 20
    identifier: News
  - name: Blog
    url: '#posts'
    weight: 22
    parent: News
  - name: Topics
    url: '#tags'
    weight: 23
    parent: News  
  - name: Solutions
    url: '#services'
    weight: 30
    identifier: Solutions
  - name: Apps
    url: 'apps/'
    weight: 31
    parent: Solutions
  - name: Software
    url: '#releases'
    weight: 32
    parent: Solutions
  - name: Code
    url: '/category/r-bloggers/'
    weight: 34
    parent: Solutions
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: 🏛️ Music & Economy
    url: https://music.dataobservatory.eu/pillar/music-economy/
    weight: 41
    parent: Data
  - name: 🏛️ Diversity & Circulation
    url: https://music.dataobservatory.eu/pillar/diversity-circulation/
    weight: 42
    parent: Data
  - name: 🏛️ Music & Society
    url: https://music.dataobservatory.eu/pillar/music-and-society/
    weight: 43
    parent: Data
  - name: 🏛️ Music Tech & Innovation
    url: https://music.dataobservatory.eu/pillar/innovation/
    weight: 44
    parent: Data
  - name: 📖 Open Science Repository
    url: 'https://zenodo.org/communities/music_observatory'
    weight: 48
    parent: Data
  - name: Resources
    url: ../resources/
    weight: 60
    identifier: Resources
  - name: Overview
    url: ../resources/
    weight: 61
    parent: Resources
  - name: Music Economy
    url: ../resources/music-economy/
    weight: 62
    parent: Resources
  - name: Diversity & Circulation
    url: ../resources/music-diversity-circulation/
    weight: 63
    parent: Resources
  - name: Music Society & Citizenship
    url: ../resources/music-society-citizenship/
    weight: 64
    parent: Resources
  - name: Tech & Innovation
    url: ../resources/music-tech-innovation/
    weight: 65
    parent: Resources
  - name: Open Music Observatory
    url: ../resources/open-music-observatory/
    weight: 66
    parent: Resources
  - name: Open Policy Analysis
    url: ../resources/opa/
    weight: 67
    parent: Resources
#    url: '#publications'
#    weight: 62
#    parent: Publications
  - name: Consortium
    url: '#contributors'
    weight: 70
    identifier: Consortium
  - name: Contact
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '#contact'
    weight: 91
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact
